version: "2"

services:
    db:
        restart: always
        image: mariadb:latest
        volumes:
            - ./mariadb/my.cnf:/etc/mysql/conf.d/frappe.cnf
            - mariadb_data:/var/lib/mysql
        environment:
            - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
            - MYSQL_USER=${MYSQL_USER}
            - MYSQL_PASSWORD=${MYSQL_PASSWORD}
            - MYSQL_DATABASE=${MYSQL_DATABASE}
    
    redis-cache:
        image: redis
        restart: always
    
    redis-queue:
        image: redis
        restart: always

    redis-socketio:
        image: redis
        restart: always

    erpnext:
        build: 
            context: ./erpnext
            args:
                - FRAPPE_USER
                - BENCH_BRANCH
                - BENCH_REPO
                - FRAPPE_BRANCH
                - FRAPPE_REPO
                - TIMEZONE
                - ERPNEXT_BRANCH
                - ERPNEXT_REPO
                - ERPNEXT_SITE
                - DOCKERIZE_VERSION
        environment:
            - FRAPPE_USER
            - ERPNEXT_BRANCH
            - ERPNEXT_REPO
            - ERPNEXT_SITE
            - ERPNEXT_PASSWORD
            - MYSQL_URI
            - MYSQL_DATABASE
            - MYSQL_PASSWORD
            - MYSQL_USER
            - MAIL_LOGIN
            - MAIL_PASSWORD
            - MAIL_PORT
            - MAIL_SERVER
            - REDIS_CACHE
            - REDIS_QUEUE
            - REDIS_SOCKETIO
            - ROOT_PASSWORD
            - ERPNEXT_SSL
            - ERPNEXT_DEVELOPER

        depends_on:
            - db
            - redis-cache
            - redis-queue
            - redis-socketio
    
    nginx:
        image: nginx:alpine
        volumes:
            - './nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro'
        ports:
            - ${NGINX_PORT}:80
        links:
            - erpnext
        volumes_from:
            - erpnext
        depends_on:
            - erpnext
    
networks:
    default:
        external:
            name: ${NETWORK}

volumes:
    mariadb_data:
        external:
            name: ${DATA}
